spring:
  datasource:
    #    url: jdbc:h2:mem:mydb
    username: pass_local
    password: passlocal123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pass_local?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    hikari:
      maximum-pool-size: 20 # default 10

  batch:
    jdbc:
      initialize-schema: always